name: Deploy Frontend
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true cygnetops/react-test npm test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Create EB application version
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION:            eu-central-1
          APP_NAME:              frontend
          VERSION_LABEL:         v-${{ github.run_number }}
        run:
          aws elasticbeanstalk create-application-version \
            --application-name $APP_NAME \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket="elasticbeanstalk-eu-central-1-621222165099",S3Key="app-${{ github.sha }}.zip"
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-621222165099
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip